# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Ingress controllers
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  #   # st2, postgres, etc..
  # - containerPort: 30443
  #   hostPort: 30443
# the six workers, 3 'system', 3 'spin'
- role: worker
  labels:
    workload: system
    node.kubernetes.io/instance-type: kind
- role: worker
  labels:
    workload: system
    node.kubernetes.io/instance-type: kind
- role: worker
  labels:
    workload: system
    node.kubernetes.io/instance-type: kind
- role: worker
  labels:
    runtime: containerd-shim-spin
    node.kubernetes.io/instance-type: kind
- role: worker
  labels:
    runtime: containerd-shim-spin
    node.kubernetes.io/instance-type: kind
- role: worker
  labels:
    runtime: containerd-shim-spin
    node.kubernetes.io/instance-type: kind